image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - yarn
    - yarn lint

deploy:
  stage: deploy
  only:
    - master
  script:
    - npx semantic-release
