image: node:latest

cache:
  paths:
    - node_modules/

lint:
  script:
    - yarn install
    - yarn lint

deploy:
  image: node:latest
  stage: deploy
  only:
    - master
  script:
    - npx semantic-release
