name: test + publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn lint

  publish-npm:
    if: contains(github.ref, 'master')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: export GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}
      - run: |
            git config --global user.name 'devdepcomp'
            git config --global user.email 'devdepcomp@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            git checkout "${GITHUB_REF:11}"
      - run: yarn
      - run: npx semantic-release
